--- #YAML:1.0
name:               App-Pimpd
version:            0.212
abstract:           Perl Interface for the Music Player Daemon 2
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Audio::MPD:           0
    Config::General:      0
    perl:                 5.010
    Term::ExtendedColor:  0
    Term::ReadLine::Gnu:  0
resources:
    bugtracker:  https://github.com/trapd00r/pimpd2/issues
    repository:  https://github.com/trapd00r/pimpd2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
